@extends('layouts.app2')

@section('location')
{{$title}}
@endsection
@section('style')
    <style>
        td.details-control, .categoryPerDate {
            background: url('../assets/image/plus.png') no-repeat center center;
            cursor: pointer;
        }

        tr.shown td.details-control {
            background: url('../assets/image/minus.png') no-repeat center center;
        }
        
    </style>
@endsection
@section('content')
    <!-- Display All Data -->
    <div class="content">
        <div class="container-fluid">

            <div class="row">
                <div class="col-md-12">
                    <div class="card">
                        <div class="card-header">
                            <div class="row">
                                <div class="col-lg-10">
                                    <h4 class="card-title"><b>Generate VAS Report</b></h4>
                                    <p class="category">Select Facilities</p>
                                </div>
                                <div class="col-lg-2">
                                </div>
                            </div>
                        </div>
                        <div class="card-content">
                            <div class="row">
                            <div class="col-md-6">
                                <div class="form-group">
                                    <select class="selectpicker form-control" data-style="btn-info" name="facilities" id="facilities">
                                        <option value="" disabled selected>Select Health Facilities.....</option>
                                    </select>
                                </div>
                            </div>
                            <div class="col-md-6">
                                <div class="form-group">
                                    <button type="button" class="btn btn-info btn-block" id="generateVASReport">Generate VAS Report</button>
                                </div>
                            </div>

                        </div>
                        </div>
                    </div>
                </div> <!-- end col-md-12 -->
            </div>

            <div class="row">
                <div class="col-md-12">
                    <div class="card">
                        <div class="card-header">
                            <div class="row">
                                <div class="col-lg-10">
                                    <h4 class="card-title"><b>CVIMS File Export</b></h4>
                                    <p class="category">File Export List</p>
                                </div>
                                <div class="col-lg-2">
                                </div>
                            </div>
                        </div>
                        <div class="card-content">
                            <table id="datatable" class="table table-bordered table-sm table-hover" cellspacing="0"
                                width="100%">
                                <!--Table head-->
                                <thead style="background-color: rgb(214, 214, 214)">
                                    <tr>
                                        <th style="width:20px;"></th>
                                        <th>Date Time Reported</th>
                                        <th>Total of Data</th>
                                        <th>Report Type</th>
                                        <th>Facility</th>
                                        <th>Generated By</th>
                                        <th>File Name</th>
                                        <th style="width: 200px;">Actions</th>
                                    </tr>
                                </thead>
                                <!--Table head-->
                                <!--Table body-->
                                <tbody>
                                </tbody>
                                <!--Table body-->
                            </table>
                        </div>
                    </div>
                </div> <!-- end col-md-12 -->
            </div>
        </div>
    </div>
    <!-- End Display All Data -->

    <!-- Modal For Add -->
    <div class="modal fade in" tabindex="-1" role="dialog" id="categoryPerDateModal">
        <div class="modal-dialog modal-lg" role="document">
            <div class="modal-content">
                <!-- Modal Header -->
                <div class="modal-header">
                    <a class="close" data-dismiss="modal">&times;</a>
                    <label id="modalDate"></label>
                </div>
                <!-- End Modal Header -->
                <div class="modal-body">
                
                    <table class="table table-bordered table-hover text-center" id="categoryPerDateTable">
                        <thead>
                            <th colspan="" class="text-center" style="background:#f3bb45; font-size:15px"><b>CATEGORY</b></th>
                            <th colspan="" class="text-center" style="background:#f3bb45; font-size:15px"><b>NUMBER OF VACCINATED</b></th>
                        </thead>
                        <tbody></tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>
    <!-- End Modal for Add -->

@endsection

@section('js')
<script>

    let categoryCountPerDateFirstDose = [];
    let categoryCountPerDateSecondDose = [];
    let vaccines = [];
    let dates = [];
    let flag = false;
    
    $(document).ready(function () {

        $.ajax({
            url:'{{ route('file-export.perspective-facility') }}',
            type:'GET',
            dataType:'JSON',
            success:function(response){
                response.forEach(data => {
                    $("select[name='facilities']").append(`<option data-icon="fa fa-hospital-o" value="${data.hf_id}">${data.hf_name}</option>`);
                });
                $("select[name='facilities']").selectpicker("refresh");
            },
        })

        datatable = $('#datatable').DataTable({
            "processing": true,
            "serverSide": true,
            "language": {
            processing: '<i style="width: 50px;" class="fa fa-spinner fa-spin fa-lg fa-fw"></i><b> Processing....</b>'},
            "ajax":{
                "url": '{{ route('file-export.find-all') }}',
                "dataType": "json",
                "type": "POST",
                "data":{ _token: "{{csrf_token()}}", "facility" : $("#facilities").val()}
            },
            "columns": [
                {
                    "className":'details-control',
                    "orderable":false,
                    "data":null,
                    "defaultContent": ''
                },
                { "data": "datetime_requested" },
                { "data": "total_of_data" },
                { "data": "export_type" },
                { "data": "facility_name" },
                { "data": "generated_by" },
                { "data": "remarks" },
                { "data": "actions" },
            ],
            "columnDefs": [
                { "orderable": false, "targets": [ 0,1,2,3,4,5,6 ] },
            ]
        });
        
        //Show other details
        $('#datatable tbody').on('click', 'td.details-control', function () {
            var tr = $(this).closest('tr');
            var row = datatable.row( tr );
    
            if ( row.child.isShown() ) {
                // This row is already open - close it
                row.child.hide();
                flag = false;
                tr.removeClass('shown');
            }
            else {
                if(flag == true){
                    swal({
                        title: "Warning!",
                        text: "Other Information is already open",
                        type: "warning",
                    });
                }else{
                    // Open this row
                    row.child( format(row.data()) ).show();
                    flag = true;
                    tr.addClass('shown');
                }
            }
        });
        
        $("#categoryPerDate").click(function(){
            alert("qwe");
        });
        
        $('#generateVASReport').on('click', function(){
            

            if(!($('#facilities').val())){
                swal({
                    title: "Warning!",
                    text: "Please select facility first!",
                    type: "warning",
                    footer: '<a href = "mailto: enterprise.cabuyao@gmail.com">Send an email to us!</a>'
                });
                return false;    
            }


            Swal.fire({
                title: 'Generate VAS Report?',
                text: "You won't be able to revert this!",
                type: 'warning',
                showCancelButton: true,
                confirmButtonColor: '#3085d6',
                cancelButtonColor: '#d33',
                confirmButtonText: 'Yes, export it!',
                html: "<b>Export File",
                footer: '<a href = "mailto: enterprise.cabuyao@gmail.com">Send an email to us!</a>'
            }).then((result) => {
                if (result.value) {

                    $.ajax({
                        url:'{{ route('file-export.exportByFacility') }}',
                        type:'POST',
                        data:{
                            '_token': '{{ csrf_token() }}',
                            'facility_id': $('#facilities').val(),
                        },
                        xhrFields: {
                            responseType: 'blob',
                        },
                        beforeSend: function(){
                            processObject.showProcessLoader();
                        },
                        success: function(result, status, xhr) {

                            var disposition = xhr.getResponseHeader('content-disposition');
                            var matches = /"([^"]*)"/.exec(disposition);
                            var filename = (matches != null && matches[1] ? matches[1] : '_VAS_REPORT.xlsx');

                            // The actual download
                            var blob = new Blob([result], {
                                type: 'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet'
                            });
                            var link = document.createElement('a');
                            link.href = window.URL.createObjectURL(blob);
                            link.download = filename;

                            document.body.appendChild(link);

                            link.click();
                            document.body.removeChild(link);
                            datatable.ajax.reload( null, false );
                            swal({
                                title: "Save!",
                                text: "Successfully Exported!",
                                type: "success",
                                html: "<b>" + filename +"<br> ",
                                footer: '<a href = "mailto: enterprise.cabuyao@gmail.com">Send an email to us!</a>'
                            });
                        },
                        complete: function(){
                            processObject.hideProcessLoader();
                            
                        },
                    });
                }
            })
        });
    });



    const fileExport = (id, type, filename, date, report ="") =>{

        Swal.fire({
                title: 'Export File?',
                text: "You won't be able to revert this!",
                type: 'warning',
                showCancelButton: true,
                confirmButtonColor: '#3085d6',
                cancelButtonColor: '#d33',
                confirmButtonText: 'Yes, save it!',
                html: "<b>" + filename +"<br> Date Last Requested: " + date ,
                footer: '<a href = "mailto: enterprise.cabuyao@gmail.com">Send an email to us!</a>'
            }).then((result) => {
                if (result.value) {
                    $.ajax({
                        xhrFields: {
                            responseType: 'blob',
                        },
                        url: "/covid19vaccine/file-export/download-file/"+ id + "/" + type + "/" + filename+'.xlsx',
                        type: "GET",
                        data:{
                            "report": report,
                        },
                        beforeSend: function(){
                            processObject.showProcessLoader();
                        },
                        success: function(result, status, xhr) {

                        var disposition = xhr.getResponseHeader('content-disposition');
                        var matches = /"([^"]*)"/.exec(disposition);
                        var filename = (matches != null && matches[1] ? matches[1] : 'salary.xlsx');

                        // The actual download
                        var blob = new Blob([result], {
                            type: 'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet'
                        });
                        var link = document.createElement('a');
                        link.href = window.URL.createObjectURL(blob);
                        link.download = filename;

                        document.body.appendChild(link);

                        link.click();
                        document.body.removeChild(link);
                        swal({
                            title: "Save!",
                            text: "Successfully Exported!",
                            type: "success",
                            html: "<b>" + filename +"<br> Date Last Requested: " + date ,
                            footer: '<a href = "mailto: enterprise.cabuyao@gmail.com">Send an email to us!</a>'
                        });

                        },
                        error: function (jqXHR, textStatus, errorThrown) {
                            swal.fire({
                                title: "Oops! something went wrong.",
                                html: "<b>" + errorThrown +"! <br>An unexpected error seems to have occured. Why not try refreshing your page? Or you can contact us if the problem persists.</b>",
                                type: "error",
                                footer: '<a href = "mailto: enterprise.cabuyao@gmail.com">Send an email to us!</a>'
                            });
                        },
                        complete: function(){
                            processObject.hideProcessLoader();
                        },
                    });
                }
            })
    }
    
    //vaccine
    const format = (d) => {
        let grade = "";
        let data = '';
        dates = [];
        categoryCountPerDateFirstDose = [];
        categoryCountPerDateSecondDose = [];
        vaccines = [];
        //set all vaccines
        for(let index = 0; index < d.vaccinatedPerVaccine.length; index++){
            vaccines.push(d.vaccinatedPerVaccine[index].vaccine);
        }
        
        data = `<div class="col-md-6">
                    <table class="table table-bordered table-hover text-center">
                        <thead>
                            <th colspan="100" class="text-center" style="background:#f3bb45"><h5><b>VACCINATED FIRST DOSE</b></h5></th>
                        </thead>
                        <tbody>
                            `;
                                
                    //Count per Vaccine
                    if(d.vaccinatedPerVaccine.length > 0){
                        data += `<tr>
                                    <td><b>VACCINE</b></td>`;
                        data +=         `<td><b>NUMBER OF VACCINATED</b> </td>
                                    </tr>`;
                        
                        for(let index = 0; index < d.vaccinatedPerVaccine.length; index++){
                            data += "<tr><td>" +  d.vaccinatedPerVaccine[index].vaccine + "</td>"; 
                            data += "<td>" + d.vaccinatedPerVaccine[index].totalCountFirstDose + "</td></tr>";
                        }
                        data += "</div>";
                    }
                    
        data +=         `</tr>
                        </tbody>
                    </table>
                    
                    <table class="table table-bordered table-hover text-center table-responsive">
                        <tbody>`;
                                
                    //Count per Vaccine
                    if(d.vaccinatedPerVaccine.length > 0){
                        data += `<tr style="background:#f3bb45"><td></td><td>Date</td>`;
                                       
                        for(let index = 0; index < d.vaccinatedPerVaccine.length; index++){ 
                            data += "<td><b>" +  d.vaccinatedPerVaccine[index].vaccine + "</b></td>";
                        }
                        
                        //count per date and vaccine
                        for(let index = 0; index < d.dates.length; index++){
                            dates.push(d.dates[index].date);
                            date = d.dates[index].date;
                            let categoryCount = {};
                            categoryCountPerDate = [];
                            
                            for(let index2 = 0; index2 < d.dates[index].categoryCountPerDate.length; index2++){
                                categoryCount = {};
                                if(d.dates[index].categoryCountPerDate[index2].countFirstDose > 0){
                                    categoryCount["date"] =  d.dates[index].date;
                                    categoryCount["vaccine"] =  d.dates[index].categoryCountPerDate[index2].vaccine;
                                    categoryCount["count"] =  d.dates[index].categoryCountPerDate[index2].countPerVaccineFirstDose;
                                    categoryCount["category"] =  d.dates[index].categoryCountPerDate[index2].category;
                                    categoryCountPerDate.push(categoryCount);
                                }
                            }
                            categoryCountPerDateFirstDose.push(categoryCountPerDate);
                            data += "<tr><td onclick='showCategoryPerDateCount(" + index + ", 1)'><button class='btn btn-xs btn-success btn-fill btn-rotate'><i class='fa fa-eye'></i></button></td><td>" + d.dates[index].date + "</td>";
                             
                            for(let index2 = 0; index2 < d.vaccinatedPerVaccine.length; index2++){
                                data += "<td>" +  d.vaccinatedPerVaccine[index2].vaccinatedPerDate[index].firstDoseCount + "</td>"; 
                            }
                            
                            data += "</tr>";
                            
                        }
                    }
                    
        data +=         `</tr>
                        </tbody>
                    </table>
                    
                    <table class="table table-bordered table-hover ">
                        <thead>
                                <td class="text-center"><b>CATEGORY</b></td>
                            <td class="text-center"><b>NUMBER OF VACCINATED</b></td>
                        </thead>
                        <tbody>
                            <tr>`;
                              
        for(let index = 0; index < d.dataFirstDose.length; index++){
            data += "<tr><td>" +  d.dataFirstDose[index].category + "</td><td class='text-center'>" + d.dataFirstDose[index].count  + "</td></tr>";
        }
        data += `</table></div>
        
                <div class="col-md-6">
                    <table class="table table-bordered table-hover text-center table-responsive">
                        <thead>
                            <th colspan="100" class="text-center" style="background:#f3bb45"><h5><b>VACCINATED SECOND DOSE</b></h5></th>
                        </thead>
                        <tbody>
                            <tr>`;
                                
                    //Count per Vaccine
                    if(d.vaccinatedPerVaccine.length > 0){
                        data += `<tr>
                                    <tr>
                                        <td><b>VACCINE</b></td>`;
                        
                        data +=         `<td><b>NUMBER OF VACCINATED</b> </td>
                                    </tr>`;
                                    
                        for(let index = 0; index < d.vaccinatedPerVaccine.length; index++){
                            data += "<tr><td>" +  d.vaccinatedPerVaccine[index].vaccine + "</td>";
                            
                            data += "<td>" + d.vaccinatedPerVaccine[index].totalCountSecondDose + "</td></tr>";
                        }
                        data += "</div>";
                    }
        data +=         `</tr>
                            </tbody>
                        </table>
                        
                    <table class="table table-bordered table-hover text-center table-responsive">
                        <tbody>`;
                                
                    //Count per Vaccine
                    if(d.vaccinatedPerVaccine.length > 0){
                        data += `<tr style="background:#f3bb45"><td></td><td>Date</td>`;
                                       
                        for(let index = 0; index < d.vaccinatedPerVaccine.length; index++){ 
                            data += "<td><b>" +  d.vaccinatedPerVaccine[index].vaccine + "</b></td>";
                        }
                        
                        //count per date and vaccine
                        for(let index = 0; index < d.dates.length; index++){
                            date = d.dates[index].date;
                            let categoryCount = {};
                            categoryCountPerDate = [];
                            
                            for(let index2 = 0; index2 < d.dates[index].categoryCountPerDate.length; index2++){
                                categoryCount = {};
                                if(d.dates[index].categoryCountPerDate[index2].countSecondDose > 0){
                                    categoryCount["date"] =  d.dates[index].date;
                                    categoryCount["vaccine"] =  d.dates[index].categoryCountPerDate[index2].vaccine;
                                    categoryCount["count"] =  d.dates[index].categoryCountPerDate[index2].countPerVaccineSecondDose;
                                    categoryCount["category"] =  d.dates[index].categoryCountPerDate[index2].category;
                                    categoryCountPerDate.push(categoryCount);
                                }
                            }
                            categoryCountPerDateSecondDose.push(categoryCountPerDate);
                            data += "<tr><td onclick='showCategoryPerDateCount(" + index + ", 2)'><button class='btn btn-xs btn-success btn-fill btn-rotate'><i class='fa fa-eye'></i></button></td><td>" + d.dates[index].date + "</td>";
                            
                            for(let index2 = 0; index2 < d.vaccinatedPerVaccine.length; index2++){
                                data += "<td>" +  d.vaccinatedPerVaccine[index2].vaccinatedPerDate[index].secondDoseCount + "</td>"; 
                            }
                            
                            data += "</tr>";
                        }
                    }
                        
        data +=     `</tr>
                            </tbody>
                        </table>
        
                        <table class="table table-bordered table-hover ">
                            <thead>
                                    <td class="text-center"><b>CATEGORY</b></td>
                                <td class="text-center"><b>NUMBER OF VACCINATED</b></td>
                            </thead>
                            <tbody>
                                <tr>`;
                            
                            
        for(let index = 0; index < d.dataSecondDose.length; index++){
            data += "<tr><td>" +  d.dataSecondDose[index].category + "</td><td class='text-center'>" + d.dataSecondDose[index].count  + "</td></tr>";
        }
        data += `</table></div>`;
        return data;
    }
    
    const showCategoryPerDateCount = (counter, dosage) =>{
        $("#categoryPerDateModal").modal("show");
        categoryArray = (dosage == 1)? categoryCountPerDateFirstDose : categoryCountPerDateSecondDose;
        let data;
        $("#modalDate").text();
        // if(categoryArray[counter].length > 0){  
        data = `<th class="text-center" style="background:#f3bb45; font-size:15px"><b>CATEGORY</b></th>`;
        for(let index = 0; index < vaccines.length; index++){
            data += `<th class="text-center" style="background:#f3bb45; font-size:15px"><b> ${vaccines[index]}</b></th>`;
        }
        // }
        
        // data = (data == null || data == "") ? "" : data;
        $("#categoryPerDateTable thead").empty();
        $("#categoryPerDateTable thead").append(data);
        $("#modalDate").text("Date : " + dates[counter]);
        
        data = "";
            if(categoryArray[counter].length > 0){
            
                data = "<tr>";
                
                index = 0
                countCategories = categoryArray[counter].length / vaccines.length;
                while(index < countCategories){
                    data += "<tr>";
                    counter2 = 0;
                    data += "<td>" + categoryArray[counter][index].category + "</td>";
                    index2 = index;
                    while(counter2 < vaccines.length){
                        data += "<td>" + categoryArray[counter][index2].count + "</td>";
                        index2 += countCategories;
                        counter2++;
                    }
                    data += "</tr>";
                    index++;
                }  
                
                data+= "</tr>";
            }
        
        data = (data == null || data == "") ? "<tr><td colspan='100'>No data available</td></tr>" : data;
        $("#categoryPerDateTable tbody").empty();
        $("#categoryPerDateTable tbody").append(data);
    }
    

</script>
@endsection
