@extends('layouts.app2')

@section('location')
{{$title}}
@endsection
@section('style')
    <style>
        td.details-control, .categoryPerDate {
            background: url('../assets/image/plus.png') no-repeat center center;
            cursor: pointer;
        }

        tr.shown td.details-control {
            background: url('../assets/image/minus.png') no-repeat center center;
        }
        
    </style>
@endsection
@section('content')
    <!-- Display All Data -->
    <div class="content">
        <div class="container-fluid">
            <div class="card">
                <div class="card-header">
                    <h4 class="card-title"><b>CVIMS File Export</b></h4>
                    <p class="category">File Export List</p>
                </div>
                <div class="card-content">
                    <div class="row">
                        <div class="col-md-6">
                            <div class="form-group">
                                <select class="selectpicker form-control" data-style="btn-info" name="facilities" id="facilities">
                                    <option value="" disabled selected>Select Health Facilities.....</option>
                                </select>
                            </div>
                        </div>
                        <div class="col-md-6">
                            <div class="form-group">
                                <button type="button" class="btn btn-info btn-block" id="generateVIMSReport">Generate VAS Report</button>
                            </div>
                        </div>
                    </div>

                    <table id="datatable2" class="table table-bordered table-sm table-hover" cellspacing="0"
                    width="100%">
                        <!--Table head-->
                        <thead style="background-color: rgb(214, 214, 214)">
                            <tr>
                                <th>Date Time Reported</th>
                                <th>Total of Data</th>
                                <th>Report Type</th>
                                <th>Facility</th>
                                <th>Generated By</th>
                                <th>File Name</th>
                                <th style="width: 200px;">Actions</th>
                            </tr>
                        </thead>
                        <!--Table head-->
                        <!--Table body-->
                        <tbody>
                        </tbody>
                        <!--Table body-->
                    </table>
                </div>
            </div>
        </div>
    </div>
    <!-- End Display All Data -->

    <!-- Modal For Add -->
    <div class="modal fade in" tabindex="-1" role="dialog" id="categoryPerDateModal">
        <div class="modal-dialog" role="document">
            <div class="modal-content">
                <!-- Modal Header -->
                <div class="modal-header">
                    <a class="close" data-dismiss="modal">&times;</a>
                    <label id="modalDate"></label>
                </div>
                <!-- End Modal Header -->
                <div class="modal-body">
                
                    <table class="table table-bordered table-hover text-center" id="categoryPerDateTable">
                        <thead>
                            <th colspan="" class="text-center" style="background:#f3bb45; font-size:15px"><b>CATEGORY</b></th>
                            <th colspan="" class="text-center" style="background:#f3bb45; font-size:15px"><b>NUMBER OF VACCINATED</b></th>
                        </thead>
                        <tbody></tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>
    <!-- End Modal for Add -->

@endsection

@section('js')
<script>

    let categoryCountPerDateFirstDose = [];
    let categoryCountPerDateSecondDose = [];
    let dates = [];
    let flag = false;
    
    $(document).ready(function () {

        $.ajax({
            url:'{{ route('file-export.perspective-facility') }}',
            type:'GET',
            dataType:'JSON',
            success:function(response){
                response.forEach(data => {
                    $("select[name='facilities']").append(`<option data-icon="fa fa-hospital-o" value="${data.hf_id}">${data.hf_name}</option>`);
                });
                $("select[name='facilities']").selectpicker("refresh");
            },
        })

        datatable2 = $('#datatable2').DataTable({
            "processing": true,
            "serverSide": true,
            "language": {
            processing: '<i style="width: 50px;" class="fa fa-spinner fa-spin fa-lg fa-fw"></i><b> Processing....</b>'},
            "ajax":{
                "url": '{{ route('vims-ir.find-all') }}',
                "dataType": "json",
                "type": "POST",
                "data":{ _token: "{{csrf_token()}}", "facility" : $("#facilities").val()}
            },
            "columns": [
                { "data": "datetime_requested" },
                { "data": "total_of_data" },
                { "data": "export_type" },
                { "data": "facility_name" },
                { "data": "generated_by" },
                { "data": "remarks" },
                { "data": "actions" },
            ],
            "columnDefs": [
                { "orderable": false, "targets": [ 0,1,2,3,4,5 ] },
            ]
        });
        
        
        $("#categoryPerDate").click(function(){
            alert("qwe");
        });
        
        $('#generateVIMSReport').on('click', function(){
            
            if(!($('#facilities').val())){
                swal({
                    title: "Warning!",
                    text: "Please select facility first!",
                    type: "warning",
                    footer: '<a href = "mailto: enterprise.cabuyao@gmail.com">Send an email to us!</a>'
                });
                return false;    
            }

            Swal.fire({
                title: 'Generate VAS Report?',
                text: "You won't be able to revert this!",
                type: 'warning',
                showCancelButton: true,
                confirmButtonColor: '#3085d6',
                cancelButtonColor: '#d33',
                confirmButtonText: 'Yes, export it!',
                html: "<b>Export File",
                footer: '<a href = "mailto: enterprise.cabuyao@gmail.com">Send an email to us!</a>'
            }).then((result) => {
                if (result.value) {

                    $.ajax({
                        url:'{{ route('export.vimsirreport') }}',
                        type:'POST',
                        data:{
                            '_token': '{{ csrf_token() }}',
                            'facility_id': $('#facilities').val(),
                        },
                        xhrFields: {
                            responseType: 'blob',
                        },
                        beforeSend: function(){
                            processObject.showProcessLoader();
                        },
                        success: function(result, status, xhr) {

                            var disposition = xhr.getResponseHeader('content-disposition');
                            var matches = /"([^"]*)"/.exec(disposition);
                            var filename = (matches != null && matches[1] ? matches[1] : '_VIMS_REPORT.xlsx');

                            // The actual download
                            var blob = new Blob([result], {
                                type: 'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet'
                            });
                            var link = document.createElement('a');
                            link.href = window.URL.createObjectURL(blob);
                            link.download = filename;

                            document.body.appendChild(link);

                            link.click();
                            document.body.removeChild(link);
                            datatable.ajax.reload( null, false );
                            swal({
                                title: "Save!",
                                text: "Successfully Exported!",
                                type: "success",
                                html: "<b>" + filename +"<br> ",
                                footer: '<a href = "mailto: enterprise.cabuyao@gmail.com">Send an email to us!</a>'
                            });
                        },
                        complete: function(){
                            processObject.hideProcessLoader();
                            
                        },
                    });
                }
            })
        });
    });



    const fileExport = (id, type, filename, date, report ="") =>{

        Swal.fire({
                title: 'Export File?',
                text: "You won't be able to revert this!",
                type: 'warning',
                showCancelButton: true,
                confirmButtonColor: '#3085d6',
                cancelButtonColor: '#d33',
                confirmButtonText: 'Yes, save it!',
                html: "<b>" + filename +"<br> Date Last Requested: " + date ,
                footer: '<a href = "mailto: enterprise.cabuyao@gmail.com">Send an email to us!</a>'
            }).then((result) => {
                if (result.value) {
                    $.ajax({
                        xhrFields: {
                            responseType: 'blob',
                        },
                        url: "/covid19vaccine/file-export/download-file/"+ id + "/" + type + "/" + filename+'.xlsx',
                        type: "GET",
                        data:{
                            "report": report,
                        },
                        beforeSend: function(){
                            processObject.showProcessLoader();
                        },
                        success: function(result, status, xhr) {

                        var disposition = xhr.getResponseHeader('content-disposition');
                        var matches = /"([^"]*)"/.exec(disposition);
                        var filename = (matches != null && matches[1] ? matches[1] : 'salary.xlsx');

                        // The actual download
                        var blob = new Blob([result], {
                            type: 'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet'
                        });
                        var link = document.createElement('a');
                        link.href = window.URL.createObjectURL(blob);
                        link.download = filename;

                        document.body.appendChild(link);

                        link.click();
                        document.body.removeChild(link);
                        swal({
                            title: "Save!",
                            text: "Successfully Exported!",
                            type: "success",
                            html: "<b>" + filename +"<br> Date Last Requested: " + date ,
                            footer: '<a href = "mailto: enterprise.cabuyao@gmail.com">Send an email to us!</a>'
                        });

                        },
                        error: function (jqXHR, textStatus, errorThrown) {
                            swal.fire({
                                title: "Oops! something went wrong.",
                                html: "<b>" + errorThrown +"! <br>An unexpected error seems to have occured. Why not try refreshing your page? Or you can contact us if the problem persists.</b>",
                                type: "error",
                                footer: '<a href = "mailto: enterprise.cabuyao@gmail.com">Send an email to us!</a>'
                            });
                        },
                        complete: function(){
                            processObject.hideProcessLoader();
                        },
                    });
                }
            })
    }


    const showCategoryPerDateCount = (counter, dosage) =>{
        $("#categoryPerDateModal").modal("show");
        let data;
        $("#modalDate").text();
        
        categoryArray = (dosage == 1)? categoryCountPerDateFirstDose : categoryCountPerDateSecondDose;
        $("#modalDate").text("Date : " + dates[counter]);
        for(let index = 0; index < categoryArray.length; index++){
        
            if(counter == index && categoryArray[index].length > 0){
                for(let index2 = 0; index2 < categoryArray[index].length; index2++){
                    data += "<tr><td>" + categoryArray[index][index2].category + "</td><td>" + categoryArray[index][index2].count + "</td></tr>";
                }  
            }
        }
        
        data = (data == null) ? "<tr><td colspan='2'>No data available</td></tr>" : data;
        $("#categoryPerDateTable tbody").empty();
        $("#categoryPerDateTable tbody").append(data);
    }
    

</script>
@endsection
